module DaVinciPDexTestKit
  SET_TO_BE_GATHERED = {AllergyIntolerance: ['pdex-AllergyIntolerance'],
                        CarePlan: ['pdex-CarePlan'],
                        CareTeam: ['pdex-CareTeam'],
                        Condition: ['pdex-Condition'],
                        Device: ['pdex-Device'],
                        DiagnosticReport: ['pdex-DiagnosticReport'],
                        DocumentReference: ['pdex-DocumentReference'],
                        Encounter: ['pdex-Encounter'],
                        ExplanationOfBenefit: ['pdex-ExplanationOfBenefit'],
                        Goal: ['pdex-Goal'],
                        Immunization: ['pdex-Immunization'],
                        Location: ['pdex-Location'],
                        MedicationDispense: ['pdex-MedicationDispense'],
                        MedicationRequest: ['pdex-MedicationRequest'],
                        Observation: ['pdex-Observation'],
                        Organization: ['pdex-Organization'],
                        Patient: ['999'],
                        Practitioner: ['pdex-Practitioner'],
                        PractitionerRole: ['pdex-PractitionerRole'],
                        Procedure: ['pdex-Procedure']
                        #TODO: What about Provenance?
                      }

  SEARCHES_BY_PRIORITY = {AllergyIntolerance: [['patient']],
                          CarePlan: [['patient', 'category']],
                          CareTeam: [['patient', 'status']],
                          Condition: [['patient', 'category'], ['patient']],
                          Device: [['patient', 'type'], ['patient']],
                          DiagnosticReport: [['patient', 'category', 'date'], ['patient', 'code'], ['patient', 'category'], ['patient']],
                          DocumentReference: [['_id'], ['patient', 'category', 'date'], ['patient', 'type'], ['patient', 'category'], ['patient']],
                          Encounter: [['_id'], ['patient', 'date'], ['patient']],
                          ExplanationOfBenefit: [['_id'], ['patient'], ['identifier'], ['_lastUpdated'], ['service-date'], ['type']],
                          Goal: [['patient']],
                          Immunization: [['patient']],
                          Location: [['name'], ['address']],
                          MedicationDispense: [['patient']],
                          MedicationRequest: [['patient', 'intent']],
                          Observation: [['patient', 'category', 'date'], ['patient', 'code'], ['patient', 'category']],
                          Organization: [['name'], ['address']],
                          Patient: [['_id'], ['identifier'], ['birthdate', 'name'], ['gender', 'name'], ['name']],
                          Practitioner: [['identifier'], ['name']],
                          PractitionerRole: [['practitioner'], ['specialty']],
                          Procedure: [['patient', 'date'], ['patient']],
                        }
end